config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'application/index'
  end

  namespace :sysadmin do
    mount Resque::Server.new, at: '/resque'
  end

  devise_for :users
  resources :projects
  resources :tasks
  resources :comment
  get '/projects', to: 'projects#index'
  get '/about', to: 'about#index'
  get '/dashboard', to: 'dashboard#index'
  root 'dashboard#index'
  get '/comment/attachment/delete', to: 'comment#delete_attachment'
  delete '/comments/:task_id/attachments/:id', to: 'comment#delete_attachment', as: 'comment_attachment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
  has_many_attached :comment_files
end

app/controllers/comment_controller.rb
class CommentController < SecureController
  before_action :set_comment, except: [:index, :create, :new, :delete_attachment]

  def index

  end

  def new

  end

  def create
    @comment = Comment.new(comment_params)
    authorize! :show, @comment
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Comment has been created."
      redirect_to controller:'tasks', action: 'show', id:@comment.task_id
    else
      flash[:danger] = "An error occurred."
      redirect_to controller:'tasks', action: 'show', id:@comment.task_id
    end

  end

  def edit
    @task = Task.find(@comment.task_id)
  end

  def update
    if  @comment.update(comment_params)
      flash[:notice] = "Comment has been updated."
      redirect_to controller:'tasks', action: 'show', id:@comment.task_id
    else
      flash[:danger] = "An error occurred."
      redirect_to controller:'tasks', action: 'show', id:@comment.task_id
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = "Comment has been deleted."
    redirect_to controller:'tasks', action: 'show', id:@comment.task_id
  end

  def comment_params
    params.require(:comment).permit(:description, :task_id, comment_files:[])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def delete_attachment
    @comment_attachment = ActiveStorage::Attachment.find(params[:id])
    @comment = Comment.find(@comment_attachment.record_id)
    @comment_attachment.purge
    redirect_to controller:'tasks', action: 'show', id: @comment.task_id
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comment/_form.html.erb
<div class="modal-body">
  <% if @comment.id.blank? %>
    <%= form_for @comment, :url => url_for(:controller => 'comment' ) do |c| %>
      <div class="modal-header">
        <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
        <h3 id="myModalLabel">New Comment</h3>
      </div>
      <b>Task Id Create: </b><%= task.id %></br>
      <b>Task Name: </b><%= task.name %>
      <p>
        <%= c.hidden_field :task_id, :value => task.id %>
        <%= c.text_area :description, size: "60x10" %>
      </p>
      <b>Attached Files: </b></br>
      <% @comment.comment_files.each do |cf| %>
        <b>Attachment: </b><%= cf.filename %></br>
      <% end %>
      <p>
        <%= file_field c, :comment_files, :multiple => true %><br>
      </p>
      <%= c.submit :class => 'btn btn-primary'%>
    <% end %>
    <div class="modal-footer">
      <button aria-hidden="true" class="btn" data-dismiss="modal">Close</button>
    </div>
  <% else %>
    <%= form_for  @comment, :url => url_for(:controller => 'comment', :method => :post, :action => :update) do |c| %>
      <b>Task Id Edit: </b><%= task.id %></br>
      <b>Task Name: </b><%= task.name %>
      <p>
        <%= c.hidden_field :task_id, :value => task.id %>
        <%= c.text_area :description, size: "60x10" %>
      </p>
      <b>Attached Files: </b></br>
      <% @comment.comment_files.each do |cf| %>
        <%= link_to cf.filename %> | <%= link_to "delete", comment_attachment_delete_path(:id => cf.id), {:style => "border-bottom:2px solid #0062cc", :class => "btn-link", data: { confirm: "Are you sure you want to delete this file?" }} %></br>
        <%= link_to "Delete", comment_attachment_path({task_id: @comment.task, id: cf.id}), :method => 'delete', :style => "border-bottom:2px solid #0062cc", :class => "btn-link", data: { confirm: "Are you sure you want to delete this file?" } %>
    <% end %>
      <p>
        <%= c.file_field :comment_files, :multiple => true %><br>
      </p>
      <%= c.submit :class => 'btn btn-primary'%>
    <% end %>
  <% end %>


</div>

app/views/comment/edit.html.erb
<h1>Update Comment</h1>

<%= render :partial => '/comment/form', :new => @comment, locals: {:task => @task}  %>

app/views/comment/new.html.erb
<%= render :partial =>  "form", :locals => {:edit => true, task: @task} %>