config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'application/index'
  end

  namespace :sysadmin do
    mount Resque::Server.new, at: '/resque'
  end

  devise_for :users
  resources :projects
  resources :tasks
  resources :comment
  get '/projects', to: 'projects#index'
  get '/about', to: 'about#index'
  get '/dashboard', to: 'dashboard#index'
  root 'dashboard#index'
  get '/comment/attachment/delete', to: 'comment#delete_attachment'
  delete '/comments/:task_id/attachments/:id', to: 'comment#delete_attachment', as: 'comment_attachment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new
    if user.admin
      can :manage, :all
    else
      can :read
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
  has_many_attached :comment_files
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :nullify
  validates :name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :assigned_to, class_name: "User", optional: true
  belongs_to :created_by, class_name: "User"
  has_many :comments
  validates :name, :due_date, :category, :status, :priority, presence: true
  # validates :category, presence: true
  # validates :status, presence: true
  # validates :prioriy, presence: true

  scope :order_by_priority, -> {
    order_by = ['CASE']
    PRIORITY_ORDERS.each_with_index do |priority, index|
      order_by << "WHEN tasks.priority='#{priority}' THEN #{index}"
    end
    order_by << 'END'
    order(order_by.join(' '))
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
  has_many :comments

  def admin?
    self.admin
  end
end

app/controllers/about_controller.rb
class AboutController < SecureController
  def index
  end
end

app/controllers/comment_controller.rb
class CommentController < SecureController
  before_action :set_comment, except: [:index, :create, :new, :delete_attachment]

  def index

  end

  def new

  end

  def create
    @comment = Comment.new(comment_params)
    authorize! :show, @comment
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "Comment has been created."
      redirect_to controller:'tasks', action: 'show', id:@comment.task_id
    else
      flash[:danger] = "An error occurred."
      redirect_to controller:'tasks', action: 'show', id:@comment.task_id
    end

  end

  def edit
    @task = Task.find(@comment.task_id)
  end

  def update
    if  @comment.update(comment_params)
      flash[:notice] = "Comment has been updated."
      redirect_to controller:'tasks', action: 'show', id:@comment.task_id
    else
      flash[:danger] = "An error occurred."
      redirect_to controller:'tasks', action: 'show', id:@comment.task_id
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = "Comment has been deleted."
    redirect_to controller:'tasks', action: 'show', id:@comment.task_id
  end

  def comment_params
    params.require(:comment).permit(:description, :task_id, comment_files:[])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def delete_attachment
    @comment_attachment = ActiveStorage::Attachment.find(params[:id])
    @comment = Comment.find(@comment_attachment.record_id)
    @comment_attachment.purge
    redirect_to controller:'tasks', action: 'show', id: @comment.task_id
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < SecureController

  def index
    @tasks = Task.order_by_priority.where(assigned_to_id: "#{current_user.id}")

    if @tasks.size == 0
      flash.now[:notice]=  "No task currently assigned to me"
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < SecureController
  before_action :set_project, except: [:index, :create, :new]

  def index
  @projects = Project.all
  end

  def new
   @project = Project.new
   authorize! :new, @project
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to projects_path

    else
      flash.now[:danger] = "An error occurred."
      render new_project_path

    end
  end

  def show
  end

  def edit
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path
  end

  def update
    if  @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to projects_path

    else
      flash[:danger] = "An error occurred."
      render "edit"
    end
    end


  private
  def project_params
    params.require(:project).permit(:name, :description)
  end

  def set_project
    @project = Project.find(params[:id])
  end

end

app/controllers/secure_controller.rb
class SecureController < ApplicationController

  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, except: [:index, :create, :new]

  def index
     @tasks = Task.order_by_priority
  end

  def new
   @task = Task.new
  end

  def create
    @task = Task.new(task_params) #question: project_id is an integer how come @task.project is properly set by this?
    #@task.project = Project.find((task_params[:project_id]))
    @task.created_by = current_user
    @task.assigned_to = current_user

    if @task.save!
      flash[:notice] = "Task has been created."
      notification = Notification.new(recipient: current_user.email)
      notification.save
    else
      flash[:danger] = "An error occurred."
    end
    redirect_to dashboard_path
  end

  def show
  end

  def edit
    unless @task.assigned_to_id == current_user.id || current_user.admin
      flash[:danger] = "Cannot edit this task."
      redirect_to dashboard_path
    end


  end

  def update
    if  @task.update(task_params)
      flash[:notice] = "Task has been updated."
      redirect_to dashboard_path

    else
      flash[:danger] = "An error occurred."
      render "edit"
    end

  end

  def destroy
    unless @task.assigned_to_id == current_user.id || current_user.admin
      flash[:danger] = "Cannot delete this task."
      redirect_to dashboard_path
    end
    @task.destroy
    flash[:notice] = "Task has been deleted."
    redirect_to dashboard_path
  end

  private
  def task_params
    params.require(:task).permit(:name, :description, :project_id, :assigned_to_id, :due_date, :category, :status, :priority)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def admin_user?
    current_user.try(:admin?)
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/secure_controller_helper.rb
module SecureControllerHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_nav_bar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">GemProject</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
        <div class="navbar-right">
          <p class="navbar-text">  Signed in as <%= current_user.email %> </p>
          <p class="navbar-text"> <%= link_to "logout", destroy_user_session_path, method: :delete %></p>
        </div>
    </div>


    <div class="wrapper">
      <!-- Sidebar -->
      <nav id="sidebar">
        <div class="sidebar-header">
          <h3>Navigate</h3>
        </div>

        <ul class="list-unstyled components">
          <li class="active">
            <%= link_to "Home", dashboard_path %>
          </li>
          <li>
            <%= link_to "Projects", projects_path %>
          </li>

          <li>
            <%= link_to "Tasks", tasks_path %>
          </li>

          <li>
            <%= link_to "About", about_path %>
          </li>



          <li>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
              <li>
                <a href="#">Page 1</a>
              </li>
              <li>
                <a href="#">Page 2</a>
              </li>
              <li>
                <a href="#">Page 3</a>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to "Create Task", {controller: "tasks", action: "new"}, {:class => "btn btn-success"}%>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Gem Project" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>



    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <% if user_signed_in? %>
    <%= render partial: "layouts/nav_bar" %>
  <% end %>

    <div class="container">
      <div class="row">

        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
    <!--/span-->
      </div><!--/row-->



    </div> <!-- /container -->
  </body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Devise" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>



    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container">
      <div class="row">

        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
    <!--/span-->
      </div><!--/row-->



    </div> <!-- /container -->
  </body>

</html>